version: "3.8"
services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/proc/:/host/proc/:ro"
      - "/sys/fs/cgroup/:/host/sys/fs/cgroup:ro"
    environment:
      DD_API_KEY: "<API Key>"
      DD_SITE: "datadoghq.com"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
    ports:
      - "8126:8126/tcp"
      - "8125:8125/udp"
    networks:
      - primary

  test-app:
    image: test-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DD_ENV: "prod"
      DD_SERVICE: "test-app-service"
      DD_VERSION: "0.0.1"
      DD_AGENT_HOST: dd-agent
      DD_TRACE_AGENT_PORT: "8126"
      DD_PROFILING_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
    labels:
      com.datadoghq.tags.env: "prod"
      com.datadoghq.tags.service: "test-app"
      com.datadoghq.tags.version: "0.0.1"
    ports:
      - "5000:5000"
    networks:
      - primary

networks:
  primary:
